const sampleListings = [
  {
    title: "Cozy Mountain Cabin",
    description: "A peaceful cabin surrounded by pine forests and snow-capped peaks.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    price: 120,
    location: "Manali",
    country: "India",
  },
  {
    title: "Luxury Beach Villa",
    description: "Ocean-facing villa with a private pool and sunset view.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    price: 350,
    location: "Goa",
    country: "India",
  },
  {
    title: "Desert Safari Camp",
    description: "Experience desert life under the stars with camel rides and bonfires.",
    image: "",
    price: 80,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Urban Apartment Loft",
    description: "Modern loft apartment in the heart of the city.",
    image: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    price: 200,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Countryside Farm Stay",
    description: "Stay close to nature on a peaceful organic farm.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    price: 90,
    location: "Nashik",
    country: "India",
  },
  {
    title: "Hilltop Treehouse",
    description: "A wooden treehouse with panoramic valley views.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    price: 150,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Historic Palace Suite",
    description: "Live like royalty in this restored heritage palace.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    price: 500,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Minimalist Studio Apartment",
    description: "Compact studio ideal for digital nomads and solo travelers.",
    image: "",
    price: 70,
    location: "Pune",
    country: "India",
  },
  {
    title: "Lakeside Cottage",
    description: "Beautiful cottage overlooking a serene lake with fishing options.",
    image: "https://images.unsplash.com/photo-1506377711771-71d4a5e8dd51",
    price: 110,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Jungle Retreat",
    description: "Eco-friendly retreat in the middle of dense tropical forest.",
    image: "https://unsplash.com/photos/courtyard-with-pool-ornate-door-and-chairs-GtlrYb2cPp4",
    price: 180,
    location: "Wayanad",
    country: "India",
  },
  
  {
    title: "Snowy Chalet Escape",
    description: "A cozy wooden chalet with a fireplace and stunning snow mountain views.",
    image: "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef",
    price: 220,
    location: "Gulmarg",
    country: "India",
  },
  {
    title: "Backwater Houseboat",
    description: "Cruise through Kerala’s tranquil backwaters on a luxury houseboat.",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
    price: 260,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Cultural Heritage Homestay",
    description: "Traditional Rajasthani home with cultural performances and local cuisine.",
    image: "https://unsplash.com/photos/jagged-rocky-mountain-peak-with-green-vegetation-MGUMUFlqKNs",
    price: 95,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Tea Estate Bungalow",
    description: "Elegant colonial bungalow amidst sprawling tea gardens.",
    image: "https://images.unsplash.com/photo-1526045612212-70caf35c14df",
    price: 170,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Forest Yoga Retreat",
    description: "Wellness resort focused on yoga, meditation, and holistic healing.",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2",
    price: 140,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Riverside Camping Site",
    description: "Adventure-filled riverside camp with rafting and bonfire nights.",
    image: "",
    price: 60,
    location: "Kullu",
    country: "India",
  },
  {
    title: "Luxury Desert Dome",
    description: "Modern geodesic domes in the desert offering a sky full of stars.",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    price: 280,
    location: "Thar Desert",
    country: "India",
  },
  {
    title: "Rustic Himalayan Homestead",
    description: "Warm homestay with local food and Himalayan valley views.",
    image: "https://images.unsplash.com/photo-1519817914152-22d216bb9170",
    price: 100,
    location: "Kasol",
    country: "India",
  },
  {
    title: "Eco Beach Hut",
    description: "Simple bamboo hut by the beach for eco-conscious travelers.",
    image: "https://images.unsplash.com/photo-1559599101-1a66f2ecdd77",
    price: 75,
    location: "Varkala",
    country: "India",
  },
  {
    title: "City Skyline Penthouse",
    description: "High-rise penthouse offering panoramic city skyline views.",
    image: "https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0",
    price: 400,
    location: "Mumbai",
    country: "India",
  },
];



module.exports = {
 data: sampleListings
};